create table cities
(
    country_id integer not null,
    id         bigint generated by default as identity,
    name       varchar(45) unique,
    primary key (id)
);

create table countries
(
    id   integer generated by default as identity,
    name varchar(45) unique,
    primary key (id)
);

create table roles
(
    id   integer generated by default as identity,
    name varchar(45),
    primary key (id)
);

create table users
(
    id         integer generated by default as identity,
    city_id    bigint,
    first_name varchar(45),
    last_name  varchar(45),
    password   varchar(45),
    username   varchar(45) unique,
    primary key (id)
);

alter table if exists cities
    add constraint FK6gatmv9dwedve82icy8wrkdmk
    foreign key (country_id)
    references countries;

alter table if exists users
    add constraint FKn36jwt4acj3il2ixvv2c0ncco
    foreign key (city_id)
    references cities;
